### ISSUE TITLE
Bug : can't pull batteries from CEF/CEU

### ISSUE THREAD

**Issue by SimonGhislain** [Tictim/GregTech-Revamped#1]
Hi.
I would like to send empty batteries from CEF/CEU to my main power production using enderchests. I tried with enderIO item conduits, hoppers, logistic pupes, etc. I can insert batteries in CEF/CEU this way, but there is no extraction possible. Probably because the CEF/CEU is like the input of a machine. Could that be fixed?

**Comment by Tictim** [comment]
This place is not for issues related to CEU, nor for personal contact.
